[package]
name = "pwrs-ui"
version = "0.0.1"
edition = "2021"

[lib]
name = "pwrs_ui"
path = "./lib.rs"

[dependencies]
maud = "*"
http = "*" 
axum = { git = "https://github.com/tokio-rs/axum", default-features = false, features = ["json", "query", "form"] }
bytes = "*"
tower = "*"