[package]
name = "prest-embed-utils"
version = "8.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
walkdir = "2.3.1"
sha2 = "0.10.5"
mime_guess = "2.0.4"
globset = "0.4.8"

[features]
lazy-embed = []
