[package]
name = "with-mongo-driver"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = "0.1"
mongodb = { version = "2.7.0", features = ["bson-uuid-1"] }
serde = { version = "1", features = ["derive"] }