[package]
name = "with-tls"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host", "tls"] }
maud = "0.25"
tokio = { version = "1.32", features = ["full"] }
