[package]
name = "with-oauth"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
pwrs = { path = "../../", features = ["host"] }
maud = "*"
tokio = { version = "*", features = ["full"] }
