[package]
name = "prest"
description = "Progressive RESTful framework"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/edezhic/prest"
repository = "https://github.com/edezhic/prest"
keywords = ["fullstack", "progressive", "RESTful", "PWA"]
categories = ["development-tools", "wasm", "web-programming"]

[workspace]
members = ["examples/*", "html/macro", "embed/macro", "embed/utils"]

[features]
host = ["axum-server"]
sw = ["wasm-bindgen", "wasm-bindgen-futures", "js-sys", "web-sys", "console_error_panic_hook"]

print-traces = ["tracing-subscriber/fmt"]
oauth = ["axum-login", "openidconnect", "random", "dot_env", "serde"]
tls = ["axum-server/tls-rustls"]
random = ["rand"]
dot_env = ["dotenv"]

sass = ["build", "grass"]
pwa = ["build", "wasm-bindgen-cli-support", "webmanifest"]
typescript = ["build", "swc", "swc_atoms", "swc_bundler", "swc_common", "swc_config", "swc_ecma_parser", "swc_ecma_ast", "swc_ecma_codegen", "swc_ecma_loader", "swc_ecma_minifier", "swc_ecma_transforms_base", "swc_ecma_transforms_typescript", "swc_ecma_visit"]
build = ["toml"]

debug-embed = ["embed-macro/debug-embed", "embed-utils/debug-embed"]

[lib]
name = "prest"
path = "./prest.rs"

[dependencies]
html-macro = { path = "html/macro" }
embed-macro = { path = "embed/macro"}
embed-utils = { path = "embed/utils"}
anyhow = "1.0.75"
itoa = "1"
bytes = "1"
http = "0.2.9" 
mime_guess = "2"
hex = "0.4.3"
tower = "0.4.13"
futures-util = "0.3.28"
once_cell = "1.18"
axum = { git = "https://github.com/tokio-rs/axum", default-features = false, features = ["query", "form"] }
tower-http = { version = "0.4.4", features = ["trace", "catch-panic", "cors", "set-header"] }
walkdir = "2.3.2"

# --- fork to switch axum to the latest(unstable) main like here
axum-login = { git = "https://github.com/edezhic/axum-login", optional = true } 
rand = { version = "0.8.5", features = ["min_const_gen"], optional = true }
tracing-subscriber = { version = "0.3.17", optional = true } 
axum-server = { version = "0.5.1", optional = true }
openidconnect = { version = "3.3.1", optional = true }
dotenv = { version = "0.15", optional = true }
serde = { version = "1", optional = true }

# Build deps:
grass = { version = "0.13.1", optional = true, default-features = false }
toml = { version = "0.8.1", optional = true }
webmanifest = { version = "1.1.1", optional = true }
wasm-bindgen-cli-support = { version = "0.2.87", optional = true }
swc = { version = "0.266.32", optional = true }
swc_atoms = { version = "0.5.9", optional = true }
swc_bundler = { version = "0.220.25", features = ["concurrent"], optional = true }
swc_common = { version = "0.32.1", features = ["tty-emitter"], optional = true }
swc_config = { version = "0.1.7", optional = true }
swc_ecma_parser = { version = "0.140", features = ["typescript"], optional = true }
swc_ecma_ast = { version = "0.109.1", optional = true }
swc_ecma_codegen = { version = "0.145.5", optional = true }
swc_ecma_loader = { version = "0.44.4", optional = true }
swc_ecma_minifier = { version = "0.187.25", optional = true }
swc_ecma_transforms_base = { version = "0.133.5", optional = true }
swc_ecma_transforms_typescript = { version = "0.183.21", optional = true }
swc_ecma_visit = { version = "0.95.1", optional = true }

# Service Worker deps:
wasm-bindgen = { version = "0.2.87", optional = true }
wasm-bindgen-futures = { version = "0.4.37", optional = true }
js-sys = { version = "0.3.64", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
[dependencies.web-sys]
version = "0.3.64"
optional = true
features = [
    "console",
    "FetchEvent", 
    "Request", 
    "ReadableStream", 
    "ReadableStreamDefaultReader",
    "Headers", 
    "ResponseInit", 
    "Response",
    "ServiceWorkerGlobalScope",
    "WorkerGlobalScope",
    "WorkerLocation",
]