[package]
name = "pwrs"
version = "0.0.1"
edition = "2021"

[workspace]
members = [
    "pwrs-build",
    "pwrs-host",
    "pwrs-sw",
    "examples/*",
]

[lib]
name = "pwrs"
path = "./pwrs.rs"

[dependencies]
maud = "*"
http = "*" 
axum = { git = "https://github.com/tokio-rs/axum", default-features = false, features = ["json", "query", "form"] }
bytes = "*"
tower = "*"

[profile.release]
lto = true
strip = true