[package]
name = "prest"
description = "Progressive RESTful framework"
version = "0.1.0"
edition = "2021"
resolver = "2" 
license = "MIT OR Apache-2.0"
homepage = "https://github.com/edezhic/prest"
repository = "https://github.com/edezhic/prest"
keywords = ["fullstack", "progressive", "RESTful", "PWA"]
categories = ["development-tools", "wasm", "web-programming"]

[lib]
name = "prest"
path = "./lib.rs"

[workspace]
members = ["build", "html/macro", "embed/macro", "embed/utils", "examples/*"]

[features]
lazy-embed = ["prest-embed-macro/lazy-embed", "prest-embed-utils/lazy-embed"]

[dependencies]
prest-html-macro = { path = "html/macro" }
prest-embed-macro = { path = "embed/macro"}
prest-embed-utils = { path = "embed/utils"}
anyhow = "1.0.75"
async-trait = "0.1.67"
itoa = "1.0.5"
bytes = "1.0"
mime_guess = "2"
hex = "0.4.3"
tower = "0.4.13"
futures = "0.3"
once_cell = "1.18"
walkdir = "2.3.2"

# host deps
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { version = "0.7.1", default-features = false, features = ["query", "form", "matched-path", "original-uri", "tokio", "http2", "tracing"] }
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread", "net", "sync"] }
tower-http = { version = "0.5.0", features = ["trace", "catch-panic", "compression-br", "limit"] }
tracing-subscriber = { version = "0.3.18", features = ["fmt"] } 

# service worker deps:
[target.'cfg(target_arch = "wasm32")'.dependencies]
axum = { version = "0.7.1", default-features = false, features = ["query", "form", "matched-path", "original-uri"] }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.64"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.64", features = ["console", "FetchEvent",  "Request",  "ReadableStream",  "ReadableStreamDefaultReader", "Headers",  "ResponseInit",  "Response", "ServiceWorkerGlobalScope", "WorkerGlobalScope", "WorkerLocation"] }

