[package]
name = "prest"
description = "Progressive RESTful framework"
version = "0.2.0"
edition = "2021"
resolver = "2" 
license = "MIT OR Apache-2.0"
homepage = "https://github.com/edezhic/prest"
repository = "https://github.com/edezhic/prest"
keywords = ["fullstack", "progressive", "RESTful", "PWA"]
categories = ["development-tools", "wasm", "web-programming"]

[lib]
name = "prest"
path = "./lib.rs"

[workspace]
members = ["build", "db/macro", "html/macro", "embed/macro", "embed/utils", "examples/*"]

[features]
lazy-embed = ["prest-embed-macro/lazy-embed", "prest-embed-utils/lazy-embed"]

[dependencies]
prest-db-macro = { path = "db/macro" }
prest-html-macro = { path = "html/macro", version = "0.1.0" }
prest-embed-macro = { path = "embed/macro", version = "0.1.0" }
prest-embed-utils = { path = "embed/utils", version = "0.1.0" }

anyhow = "1.0.77"
async-trait = "0.1.75"
itoa = "1"
mime_guess = "2"
hex = "0.4"
tower = "0.4.13"
futures = "0.3"
once_cell = "1.18"
tracing = "0.1.40"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
time = { version = "0.3", features = ["wasm-bindgen"] } 

# host
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = "0.7.3"
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread", "net", "sync"] }
tower-http = { version = "0.5", features = ["trace", "catch-panic", "compression-br", "limit"] }
tracing-subscriber = { version = "0.3.18", features = ["fmt", "chrono", "env-filter"] } 
tower-livereload = "0.9.1"
gluesql = { version = "0.15", default-features = false, features = ["sled-storage", "shared-memory-storage"]}
tower-sessions = "0.9"
uuid = { version = "1.6", features = ["v4", "serde"] }
axum-login = "0.12"
dotenvy = "0.15"
openidconnect = "3.4"
password-auth = "1"

# service worker
[target.'cfg(target_arch = "wasm32")'.dependencies]
axum = { version = "0.7.3", default-features = false, features = ["query", "form", "matched-path", "original-uri", "tracing"] }
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4"
js-sys = "0.3.58"
console_error_panic_hook = "0.1.7"
tracing-web = "0.1.3"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "time"] }
web-sys = { version = "0.3.64", features = ["console", "FetchEvent",  "Request",  "ReadableStream",  "ReadableStreamDefaultReader", "Headers",  "ResponseInit",  "Response", "ServiceWorkerGlobalScope", "WorkerGlobalScope", "WorkerLocation"] }
gluesql = { version = "0.15", default-features = false, features = ["shared-memory-storage"]}
uuid = { version = "1.6", features = ["v4", "serde", "js"] }
