[package]
name = "prest"
description = "Progressive RESTful framework"
version = "0.1.0-alpha"
edition = "2021"
resolver = "2" 
license = "MIT OR Apache-2.0"
homepage = "https://github.com/edezhic/prest"
repository = "https://github.com/edezhic/prest"
keywords = ["fullstack", "progressive", "RESTful", "PWA"]
categories = ["development-tools", "wasm", "web-programming"]

[lib]
name = "prest"
path = "./lib.rs"

[workspace]
members = ["examples/*", "html/macro", "embed/macro", "embed/utils"]

[features]
build-pwa = ["toml", "wasm-bindgen-cli-support", "webmanifest"]
lazy-embed = ["embed-macro/lazy-embed", "embed-utils/lazy-embed"]

[dependencies]
html-macro = { path = "html/macro" }
embed-macro = { path = "embed/macro"}
embed-utils = { path = "embed/utils"}
anyhow = "1.0.75"
async-trait = "*"
itoa = "1"
bytes = "1"
mime_guess = "2"
hex = "0.4.3"
tower = "0.4.13"
futures = "0.3"
once_cell = "1.18"
axum = { git = "https://github.com/tokio-rs/axum", default-features = false, features = ["query", "form", "matched-path", "original-uri"] }
walkdir = "2.3.2"

# build deps:
toml = { version = "0.8.1", optional = true }
webmanifest = { version = "1.1.1", optional = true }
wasm-bindgen-cli-support = { version = "0.2.87", optional = true }

# host deps:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.33.0", features = ["rt", "rt-multi-thread", "net"] }
hyper-server = "0.6.0"

# service worker deps:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.64"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3.64", features = ["console", "FetchEvent",  "Request",  "ReadableStream",  "ReadableStreamDefaultReader", "Headers",  "ResponseInit",  "Response", "ServiceWorkerGlobalScope", "WorkerGlobalScope", "WorkerLocation"] }

