[package]
name = "with-tracing"
version = "0.0.1"
edition = "2021"

[lib]
name = "serve"
path = "./serve.rs"

[[bin]]
name = "serve"
path = "./serve.rs"

[features]
default = ["host"]
host = ["pwrs/host", "pwrs/build", "tokio/full", "rust-embed"]
sw = ["pwrs/sw", "wasm-bindgen", "wasm-bindgen-futures"]

[dependencies]
pwrs = { path = "../../" }
maud = "*"
tokio = { version = "*", optional = true }
rust-embed = { version = "*", features = ["interpolate-folder-path"], optional = true }
wasm-bindgen = { version = "*", optional = true }
wasm-bindgen-futures = { version = "*", optional = true }

[build-dependencies]
pwrs = { path = "../../" }
