[package]
name = "blog"
version = "0.0.1"
edition = "2021"

[lib]
path = "./serve.rs"

[[bin]]
name = "serve"
path = "./serve.rs"

[features]
default = ["host"]
host = ["prest/host", "tokio"]
sw = ["prest/sw", "wasm-bindgen", "wasm-bindgen-futures"]

[dependencies]
prest = { path = "../../" }
markdown = "1.0.0-alpha.14"

tokio = { version = "*", optional = true, features = ["rt", "net", "macros"] }
wasm-bindgen = { version = "0.2.87", optional = true }
wasm-bindgen-futures = { version = "0.4.37", optional = true }

[build-dependencies]
prest = { path = "../../", features = ["pwa"] }
