[package]
name = "blog"
edition = "2021"

[lib]
name = "shared"
path = "./shared.rs"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../" }
wasm-bindgen = "0.2"
markdown = "1.0.0-alpha.16"

[build-dependencies]
prest-build = { path = "../../build" }
