[package]
name = "into-wasi-host"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host-wasi"] }
tokio_wasi = { version = "1", features = ["rt", "macros", "net", "time", "io-util"] }
