[package]
name = "with-openid-google"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../" }
axum-login = "0.10.2"
tower-sessions = "0.7.0"
openidconnect = "3.4.0"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1.74"
