[package]
name = "with-sqlx-sqlite"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = "0.1"
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls", "sqlite", "macros" ] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1.6", features = ["v4"] }