[package]
name = "scraper"
edition = "2021"

[dependencies]
prest = { path = "../../" }
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.11", default-features=false, features = ["rustls-tls"] }
scraper = "0.18"
futures = "0.3"
