[package]
name = "into-wasi"
edition = "2021"

[dependencies]
prest = { path = "../../" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio_wasi = { version = "1", features = ["rt", "macros", "net", "time", "io-util"] }
hyper_wasi = { version = "0.15", features = ["full"] }