[package]
name = "with-https"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host", "tls"] }
tokio = { version = "*", features = ["full"] }
