[package]
name = "todo-pwa"
edition = "2021"

[dependencies]
prest = "0.2"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"

[build-dependencies]
prest-build = { path = "../../build/", version = "0.2" }

