[package]
name = "with-typescript"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host"] }
tokio = "*"

[build-dependencies]
prest = { path = "../../", features = ["typescript"] }
