[package]
name = "with-ui-typescript"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host"] }
tokio = "*"
rust-embed = { version = "8", features = ["interpolate-folder-path"] }

[build-dependencies]
prest = { path = "../../", features = ["typescript"] }
