[package]
name = "with-diesel-postgres"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host", "dot_env"] }
tokio = { version = "1.32", features = ["full"] }
diesel = { version = "2.1.0", features = ["postgres"] }
