[package]
name = "with-turbosql-sqlite"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = "0.1"
serde = { version = "1", features = ["derive"] }
turbosql = "0.9"