[package]
name = "with-swc-typescript"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = "0.1"

[build-dependencies]
prest-build = "0.1"
anyhow = "1"
swc = "0.266.32"
swc_atoms = "0.5.9"
swc_bundler = { version = "0.220.25", features = ["concurrent"] }
swc_common = { version = "0.32.1", features = ["tty-emitter"] }
swc_config = "0.1.7"
swc_ecma_parser = { version = "0.140", features = ["typescript"] }
swc_ecma_ast = "0.109.1"
swc_ecma_codegen = "0.145.5"
swc_ecma_loader = "0.44.4"
swc_ecma_minifier = "0.187.25"
swc_ecma_transforms_base = "0.133.5"
swc_ecma_transforms_typescript = "0.183.21"
swc_ecma_visit = "0.95.1"

