[package]
name = "with-swc-typescript"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../" }

[build-dependencies]
prest-build = "0.1"
anyhow = "1"
swc = "0.270.7"
swc_atoms = "0.6.5"
swc_bundler = { version = "0.223.5", features = ["concurrent"] }
swc_common = { version = "0.33.12", features = ["tty-emitter"] }
swc_config = "0.1.9"
swc_ecma_parser = { version = "0.141.33", features = ["typescript"] }
swc_ecma_ast = "0.110.15"
swc_ecma_codegen = "0.146.47"
swc_ecma_loader = "0.45.13"
swc_ecma_minifier = "0.190.5"
swc_ecma_transforms_base = "0.135.3"
swc_ecma_transforms_typescript = "0.186.5"
swc_ecma_visit = "0.96.15"

