[package]
name = "ui"
version = "0.0.1"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
maud = { git = "https://github.com/lambda-fairy/maud" }
axum = { git = "https://github.com/tokio-rs/axum", default-features = false }
http = "*"
bytes = "*"