[package]
name = "todo-pwa-auth"
edition = "2021"

[dependencies]
prest = { version = "0.2", features = ["auth"] }
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"

[build-dependencies]
prest-build = "0.2"
