[package]
name = "todo-pwa-auth"
edition = "2021"

[dependencies]
prest = { path = "../../", features = ["auth"] }
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"

[build-dependencies]
prest-build = { path = "../../build" }
