[package]
name = "with-tracing-subscriber"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../" }
tracing-subscriber = { version = "*", features = ["fmt"] } 
tower-http = { version = "*", features = ["trace"] }

