[package]
name = "with-tracing-subscriber"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../", features = ["host"] }
tokio = { version = "*", features = ["full"] }
tracing-subscriber = { version = "*", features = ["fmt"] } 
tower-http = { version = "*", features = ["trace"] }

