[package]
name = "with-grass-scss"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = "0.1"

[build-dependencies]
prest-build = "0.1"
grass = { version = "0.13.1", default-features = false }

