[package]
name = "with-grass-scss"
edition = "2021"

[[bin]]
name = "serve"
path = "./serve.rs"

[dependencies]
prest = { path = "../../" }

[build-dependencies]
prest-build = "0.1"
grass = { version = "0.13.1", default-features = false }

